### ISSUE TITLE
Problem suggestor

### ISSUE THREAD

**Issue by Ahasun** [rudradesai200/CFViewer#14]
I like your website.But I have a question.

In A2OJ Ahmed Aly gathered all problem in such a way that after solving almost any problem you will learn something new.
 
Of what basis your website suggest problems?Is it like A2OJ or its suggest randomly(means rating wise)?If answer is randomly then why I'll use an extra website when I can easily get it from codeforces?So try to change this strategy.Otherwise after some month your website will be useless and your hard work will go in vain.

**Comment by rudradesai200** [comment]
Thanks for the suggestion. But, problem suggestion is not random. It is based on the category type and ratings of the problems you solved earlier.  In a few days, I will integrate the problem tags suggestion also along with it. Please let me know if you think I can add more to it.

**Comment by Ahasun** [comment]
Thanks for the latest update. :) 

I think User solved and Rating

**Comment by Ahasun** [comment]
And there is an another problem.

Suppose my rating is x.Problem suggestor suggest me problem of rating x+10/20 to x+400.
Here lower bound is to low and also upper bound is two high .In my opinion lower bound should be x+100 and upper should be like x+200/300...400 is to high...

and also white color of this  website is too dazzling.Try to follow the white color of codeforces. Also font.
