### ISSUE TITLE
Bug Removal -- "Changing number of entries in tables doesn't change number of entries shown"

### ISSUE THREAD

**Issue by Unnati1401** [rudradesai200/CFViewer#3]
Whenever the number of entries is changed to any number other than 10, the number of problems shown are still 10.

**Comment by rudradesai200** [comment]
Hii Unnati, Thanks for pointing out the error. Can you please explain it more clearly? Or if it's possible to attach any image to it.

**Comment by Unnati1401** [comment]
I have attached two images. On changing entries count in the random
problems section, the number of problems displayed must change which is not
happening. I have changed the count to 25 but it is showing me only 10
problems.

**Comment by rudradesai200** [comment]
I am really sorry, Unnati, But, the images you shared are not visible here. I think you replied directly to the GitHub email, that's why it is happening. Can you please upload the images from the main website?

**Comment by Unnati1401** [comment]
Here, I changed the entries to 25.
![Screenshot 1](https://user-images.githubusercontent.com/52351744/85127437-0ab3c180-b24d-11ea-9587-6c2ee6492a6d.png)
Here, it is showing me only 10 problems.
![Screenshot 2](https://user-images.githubusercontent.com/52351744/85127462-156e5680-b24d-11ea-9705-f9263caf5a32.png)

**Comment by rudradesai200** [comment]
Ohh okay. Thanks for pointing it out. It will be updated soon!
