### ISSUE TITLE
Feature Add -- "Do not show tags checkbox on Problems Page and suggested problems page"

### ISSUE THREAD

**Issue by tydomaster** [rudradesai200/CFViewer#6]
Hey there! I think you should add "Do not show tags for unsolved problems" checkbox at [here](http://www.rudradesai.in/cfviewer/suggest/problem) and [here](http://www.rudradesai.in/cfviewer/problems/) like on Codeforces ([screen](http://prntscr.com/t2ui51))

**Comment by rudradesai200** [comment]
Yeah, I had that in mind for quite a long time, but I was not able to code it up using javascript. Anyways, I will again try it. Thanks for pointing it out!!

**Comment by rudradesai200** [comment]
Added show/hide tags button: https://github.com/rudradesai200/CFViewer/commit/16f92f68b42de8bba58f6fe4f85a1328aa7850d7
